version: '3.9'

networks:
  nginx-laravel:

services:

  #PHP service
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: '${APP_NAME}-server'
    working_dir: /var/www/html/
    volumes:
      - ./sources:/var/www/html
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./docker/server/php/php-xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug-settings.ini
    networks:
      - nginx-laravel

  #nginx service
  nginx:
    image: nginx:alpine
    container_name: '${APP_NAME}-nginx'
    tty: true
    ports:
      - '${APP_PORT}:80'
      - '${SSL_PORT}:443'
    volumes:
      - ./docker/config/conf.d/:/etc/nginx/conf.d/
      - ./docker/logs/nginx:/var/log/nginx/
      - ./docker/server/certs:/var/www/certs/
      - ./sources/cms-laravel:/var/www/html
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}'
    depends_on:
      - server
      - db_server
    networks:
      - nginx-laravel

  #DB service
  db_server:
    image: mariadb
    container_name: '${APP_NAME}-db'
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./docker/logs/db/query.log:/var/log/query.log
    ports:
      - '${DB_PORT}:3306'
    healthcheck:
      test: mysqladmin ping -h ${IP_DB_SERVER} -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - nginx-laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_${APP_NAME}
    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:${APP_PORT}'
    environment:
      PMA_HOST: db_server
    networks:
      - nginx-laravel
  redis:
    image: redis
    container_name: redis_${APP_NAME}
    hostname: redis
    restart: 'on-failure'
    ports:
      - '${REDIS_PORT}:6379'
volumes:
  db_data: